### ISSUE TITLE
能够获取每个点否是为遮挡点？

### ISSUE THREAD

**Issue by junedgar** [HongwenZhang/ECT-FaceAlignment#2]
你好，谢谢你的开源。
我拜读了你的论文，每个点是否是遮挡点应该有概率输出的，这边如何提取这个信息？
给您添麻烦啦！
@HongwenZhang

**Comment by HongwenZhang** [comment]
Hi junedgar, 
这个概率可通过函数 [rspimage.calculate_evidence](https://github.com/HongwenZhang/ECT-FaceAlignment/blob/master/landmark_detection/rspimage.py#L25) 提取。

**Comment by junedgar** [comment]
好的，谢谢！
